testing to see if I can catch the warning for v6 is out of date

diff --git a/.github/actions/fetch-beamline-profiles/action.yml b/.github/actions/fetch-beamline-profiles/action.yml
--- a/.github/actions/fetch-beamline-profiles/action.yml
+++ b/.github/actions/fetch-beamline-profiles/action.yml
@@ -21,6 +21,18 @@ runs:
         git clone -b "${BRANCH}" "https://github.com/${REPO_SLUG}" ${CLONED_REPO}
         echo "::endgroup::"
 
+    - name: Check pixi to be up to date
+      continue-on-error: true
+      shell: bash -leo pipefail {0}
+      run: |
+        echo "::group::Check pixi to be up to date"
+        pixi install --locked --manifest-path ${CLONED_REPO}/pixi.toml
+        if [ pixi install --locked --manifest-path ${CLONED_REPO}/pixi.toml | grep "WARN" ]; then
+            echo "pixi.toml not found in ${CLONED_REPO}. Exiting..."
+            exit 1
+        fi
+        echo "::endgroup::"
+
     - name: Install pixi profile environment
       shell: bash -leo pipefail {0}
       run: |
